// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3fijv_f_1-X7lIRlo4QIDXprZWwJJg4g',
    appId: '1:338223207419:web:21c05fa808d7c66813b15e',
    messagingSenderId: '338223207419',
    projectId: 'instafeed-87fec',
    authDomain: 'instafeed-87fec.firebaseapp.com',
    storageBucket: 'instafeed-87fec.appspot.com',
    measurementId: 'G-6J9K5GK2DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb8Y8Br-f9s0jsxLT-TQ13czG9NDobWqI',
    appId: '1:338223207419:android:0001cbb5ba81448413b15e',
    messagingSenderId: '338223207419',
    projectId: 'instafeed-87fec',
    storageBucket: 'instafeed-87fec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4IcgpcrLbNZrc12iy1Aa1oDg5IJn8pKk',
    appId: '1:338223207419:ios:0af321b2dcbf5ce513b15e',
    messagingSenderId: '338223207419',
    projectId: 'instafeed-87fec',
    storageBucket: 'instafeed-87fec.appspot.com',
    iosBundleId: 'com.example.instagramCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4IcgpcrLbNZrc12iy1Aa1oDg5IJn8pKk',
    appId: '1:338223207419:ios:269d9391e7d5ca0c13b15e',
    messagingSenderId: '338223207419',
    projectId: 'instafeed-87fec',
    storageBucket: 'instafeed-87fec.appspot.com',
    iosBundleId: 'com.example.instagramCloneApp.RunnerTests',
  );
}
